import type { CaptureResult } from '../../../../packages/schema';

export const DEMO_CAPTURE: CaptureResult = {
  capture: {
    id: 'cap_demo_docs',
    url: 'https://docs.webrag.local/v1/oauth',
    canonicalUrl: 'https://docs.webrag.local/v1/oauth',
    title: 'Authentication API Reference',
    mode: 'page',
    timestamp: '2026-09-07T00:00:00.000Z',
    extractorVersion: 'webrag-dom/0.2.0',
    contentHash: 'hash_demo_capture',
  },
  blocks: [
    {
      id: 'blk_1',
      type: 'heading',
      content: 'Authentication API Reference',
      headingPath: ['Authentication API Reference'],
      sourceAnchor: {
        blockId: 'blk_1',
        headingPath: ['Authentication API Reference'],
        cssSelector: 'main > h1',
        textQuote: { exact: 'Authentication API Reference' },
      },
      contentHash: 'hash_blk_1',
      included: true,
      attributes: { headingLevel: 1 },
    },
    {
      id: 'blk_2',
      type: 'paragraph',
      content: 'Welcome to the WebRAG Studio authentication docs. This reference explains how to issue, refresh, and revoke bearer tokens for API requests.',
      headingPath: ['Authentication API Reference'],
      sourceAnchor: {
        blockId: 'blk_2',
        headingPath: ['Authentication API Reference'],
        cssSelector: 'main > p:nth-of-type(1)',
        textQuote: { exact: 'Welcome to the WebRAG Studio authentication docs.' },
      },
      contentHash: 'hash_blk_2',
      included: true,
    },
    {
      id: 'blk_3',
      type: 'callout',
      content: 'Important: Never expose client secrets or API keys in frontend code or public repositories. Store secrets securely on your backend service.',
      headingPath: ['Authentication API Reference'],
      sourceAnchor: {
        blockId: 'blk_3',
        headingPath: ['Authentication API Reference'],
        cssSelector: 'main > .callout',
        textQuote: { exact: 'Never expose client secrets or API keys' },
      },
      contentHash: 'hash_blk_3',
      included: true,
      attributes: { calloutKind: 'WARNING' },
    },
    {
      id: 'blk_4',
      type: 'heading',
      content: 'Token Generation',
      headingPath: ['Authentication API Reference', 'Token Generation'],
      sourceAnchor: {
        blockId: 'blk_4',
        headingPath: ['Authentication API Reference', 'Token Generation'],
        cssSelector: 'main > h2:nth-of-type(1)',
        textQuote: { exact: 'Token Generation' },
      },
      contentHash: 'hash_blk_4',
      included: true,
      attributes: { headingLevel: 2 },
    },
    {
      id: 'blk_5',
      type: 'paragraph',
      content: 'To acquire an access token, send a POST request to the /oauth/token endpoint with valid client credentials.',
      headingPath: ['Authentication API Reference', 'Token Generation'],
      sourceAnchor: {
        blockId: 'blk_5',
        headingPath: ['Authentication API Reference', 'Token Generation'],
        cssSelector: 'main > p:nth-of-type(2)',
        textQuote: { exact: 'To acquire an access token' },
      },
      contentHash: 'hash_blk_5',
      included: true,
    },
    {
      id: 'blk_6',
      type: 'code',
      content: 'curl -X POST https://api.webrag.local/v1/oauth/token \\\n  -H "Content-Type: application/json" \\\n  -d \'{"client_id": "demo_app", "grant_type": "client_credentials"}\'',
      headingPath: ['Authentication API Reference', 'Token Generation'],
      sourceAnchor: {
        blockId: 'blk_6',
        headingPath: ['Authentication API Reference', 'Token Generation'],
        cssSelector: 'main > pre > code',
        textQuote: { exact: 'curl -X POST https://api.webrag.local/v1/oauth/token' },
      },
      contentHash: 'hash_blk_6',
      included: true,
      attributes: { codeLanguage: 'bash' },
    },
    {
      id: 'blk_7',
      type: 'heading',
      content: 'Supported Scopes',
      headingPath: ['Authentication API Reference', 'Supported Scopes'],
      sourceAnchor: {
        blockId: 'blk_7',
        headingPath: ['Authentication API Reference', 'Supported Scopes'],
        cssSelector: 'main > h2:nth-of-type(2)',
        textQuote: { exact: 'Supported Scopes' },
      },
      contentHash: 'hash_blk_7',
      included: true,
      attributes: { headingLevel: 2 },
    },
    {
      id: 'blk_8',
      type: 'list',
      content: '- read:blocks - Allows extracting semantic page blocks.\n- write:chunks - Permits chunking and vector storage operations.\n- execute:rag - Grants access to local similarity retrieval and LLM answer generation.',
      headingPath: ['Authentication API Reference', 'Supported Scopes'],
      sourceAnchor: {
        blockId: 'blk_8',
        headingPath: ['Authentication API Reference', 'Supported Scopes'],
        cssSelector: 'main > ul',
        textQuote: { exact: 'read:blocks - Allows extracting semantic page blocks.' },
      },
      contentHash: 'hash_blk_8',
      included: true,
      attributes: { listKind: 'unordered' },
    },
  ],
};
